name: Chrome
on: 
    push:
    schedule:
       - cron: '0 0,6,12,18 * * *'
jobs: 
   eslint:
     runs-on: ubuntu-22.04
     name: Static code analiysis
     steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
   chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          CYPRESS_USER_NAME: ${{ secrets.USER_NAME }}
          CYPRESS_USER_PASS: ${{ secrets.USER_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./cypress/reports/html

